version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  yarn-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  yarn-build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn build
workflows:
  yarn-test-build:
    jobs:
      - yarn-test
      - yarn-build
