# versions
version: 2.1
# orbs
## orbs executors commands

aliases:
  - &docker
    - image: circleci/openjdk:8-jdk-node-browsers

# jobs
jobs:
  yarn-ci:
    docker: *docker
    steps:
      - run: npx danger ci
  yarn-test:
    docker: *docker
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test
  yarn-build:
    docker: *docker
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
workflows:
  yarn-test-build:
    jobs:
      - yarn-ci
      - yarn-build
